apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: cron-workflow
spec:
  schedule: "0 */6 * * *"
  workflowSpec:
    arguments:
      parameters:
        - name: configuration-overrides
        - name: job-version
          value: dev-222
    workflowTemplateRef:
      name: workflow-template